FROM python:3.12


WORKDIR /app


COPY requirements.txt .
COPY tasks.py .


RUN pip install --no-cache-dir -r requirements.txt


CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "-c", "${CELERY_WORKER_CONCURRENCY}"]
