### Submit Prompt
POST http://{{base_url}}/submit
Content-Type: application/json
x-token: {{token}}
Accept: application/json

{
  "prompt": "سلام، جهان!"
}

> {%
    client.global.set("task_id", response.body.task_id)
%}

### Get Status
GET http://{{base_url}}//status/{{task_id}}
Content-Type: application/json
x-token: {{token}}
Accept: application/json

### Get Result
GET http://{{base_url}}/result/{{task_id}}
Content-Type: application/json
x-token: {{token}}
Accept: application/json